### ISSUE TITLE
Update plugin wiki pages

### ISSUE THREAD

**Issue by jwMaxwell** [devcodeabode/MoDiBo#17]
**Describe the bug**
The wiki pages for plugin blueprints refer to `spikeKit`, which is an unimplemented legacy module.

**Solution**
Replace referenced to `spikeKit` with `utils`

**Comment by brandoningli** [comment]
The wiki pages will not be the final home for these blueprints. They're on the wiki as a shared space for project leads to finalize the interface before committing them to the template repos, for which an Issue should be filed once finalized. Closing this issue.
