### ISSUE TITLE
Create Plugin folder and loading function

### ISSUE THREAD

**Issue by jwMaxwell** [devcodeabode/MoDiBo#5]
main.js must contain a function, which loads all plugins from the plugin folder

Plugin folder will be in the project directory

**Dependencies**

- [x] #8 for config integration
- [x] Blueprint Plugin interface finalization

**Comment by brandoningli** [comment]
Similar to Spike-2, all plugins should have a standardized interface. This Issue is blocked until that is set in stone.

**Comment by brandoningli** [comment]
Work will begin on the overall structure of the plugin loader, but cannot be finalized without finalizing plugin structure first. Therefore, work will continue but the blocked label remains.

**Comment by brandoningli** [comment]
This also depends on #8 to be able to interface with the configuration and only load enabled plugins.
