### ISSUE TITLE
Optional webhook for logging

### ISSUE THREAD

**Issue by jwMaxwell** [devcodeabode/MoDiBo#7]
**Is your feature request related to a problem? Please describe.**
If no webhook url is provided, the bot will refuse to start

**Describe the solution you'd like**
If no webhook url is provided in the `.env` file, the bot should just not enable the Discord logger and log a warning indicating such.

**Dependencies**

- [ ] #8 to implement a toggle for enabling/disabling discord logging. This is required so that no warning is logged for a lack of webhook when that logging is disabled.

**Comment by brandoningli** [comment]
Note that this is distinct from the Discord logging toggle proposed in devcodeabode/MoDiBo#8 , as this one assumes you'd like to use Discord to log, but didn't give a valid webhook.

**Comment by brandoningli** [comment]
Depends on #8 implementing a config key for enabling/disabling Discord logging.

**Comment by brandoningli** [comment]
Fixed as part of #8
